// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts    string
	Permissions string
	RoleUser    string
	Roles       string
}{
	Accounts:    "accounts",
	Permissions: "permissions",
	RoleUser:    "role_user",
	Roles:       "roles",
}
