// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("Permissions", testPermissionsUpsert)

	t.Run("RoleUsers", testRoleUsersUpsert)

	t.Run("Roles", testRolesUpsert)
}
