// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testHellos(t *testing.T) {
	t.Parallel()

	query := Hellos()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testHellosDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHellosQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Hellos().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHellosSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := HelloSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testHellosExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := HelloExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Hello exists: %s", err)
	}
	if !e {
		t.Errorf("Expected HelloExists to return true, but got false.")
	}
}

func testHellosFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	helloFound, err := FindHello(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if helloFound == nil {
		t.Error("want a record, got nil")
	}
}

func testHellosBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Hellos().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testHellosOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Hellos().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testHellosAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	helloOne := &Hello{}
	helloTwo := &Hello{}
	if err = randomize.Struct(seed, helloOne, helloDBTypes, false, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}
	if err = randomize.Struct(seed, helloTwo, helloDBTypes, false, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = helloOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = helloTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Hellos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testHellosCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	helloOne := &Hello{}
	helloTwo := &Hello{}
	if err = randomize.Struct(seed, helloOne, helloDBTypes, false, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}
	if err = randomize.Struct(seed, helloTwo, helloDBTypes, false, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = helloOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = helloTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func helloBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func helloAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func helloAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func helloBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func helloAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func helloBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func helloAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func helloBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func helloAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Hello) error {
	*o = Hello{}
	return nil
}

func testHellosHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Hello{}
	o := &Hello{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, helloDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Hello object: %s", err)
	}

	AddHelloHook(boil.BeforeInsertHook, helloBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	helloBeforeInsertHooks = []HelloHook{}

	AddHelloHook(boil.AfterInsertHook, helloAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	helloAfterInsertHooks = []HelloHook{}

	AddHelloHook(boil.AfterSelectHook, helloAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	helloAfterSelectHooks = []HelloHook{}

	AddHelloHook(boil.BeforeUpdateHook, helloBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	helloBeforeUpdateHooks = []HelloHook{}

	AddHelloHook(boil.AfterUpdateHook, helloAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	helloAfterUpdateHooks = []HelloHook{}

	AddHelloHook(boil.BeforeDeleteHook, helloBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	helloBeforeDeleteHooks = []HelloHook{}

	AddHelloHook(boil.AfterDeleteHook, helloAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	helloAfterDeleteHooks = []HelloHook{}

	AddHelloHook(boil.BeforeUpsertHook, helloBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	helloBeforeUpsertHooks = []HelloHook{}

	AddHelloHook(boil.AfterUpsertHook, helloAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	helloAfterUpsertHooks = []HelloHook{}
}

func testHellosInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testHellosInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(helloColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testHellosReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testHellosReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := HelloSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testHellosSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Hellos().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	helloDBTypes = map[string]string{`ID`: `integer`, `Value`: `character varying`}
	_            = bytes.MinRead
)

func testHellosUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(helloPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(helloAllColumns) == len(helloPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, helloDBTypes, true, helloPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testHellosSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(helloAllColumns) == len(helloPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Hello{}
	if err = randomize.Struct(seed, o, helloDBTypes, true, helloColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, helloDBTypes, true, helloPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(helloAllColumns, helloPrimaryKeyColumns) {
		fields = helloAllColumns
	} else {
		fields = strmangle.SetComplement(
			helloAllColumns,
			helloPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := HelloSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testHellosUpsert(t *testing.T) {
	t.Parallel()

	if len(helloAllColumns) == len(helloPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Hello{}
	if err = randomize.Struct(seed, &o, helloDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Hello: %s", err)
	}

	count, err := Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, helloDBTypes, false, helloPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Hello struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Hello: %s", err)
	}

	count, err = Hellos().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
